spring:
  application:
    name: wizzair2025
  config:
    import:
      - "classpath:wizz.yml"
      - "classpath:auth0.yml"
      - "classpath:ssl.yml"

  datasource:
    url: jdbc:mysql://localhost:3306/wizzair2025
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbName: wizzair2025
    mysqldump-path: C:\Program Files\MySQL\MySQL Server 8.0\bin\mysqldump.exe

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate.format_sql: true

  cache:
    type: redis
    redis:
      time-to-live: 1h

  data:
    redis:
      host: localhost
      port: 6379
      password:

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    ua.hudyma: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.data.repository.config.RepositoryConfigurationExtensionSupport: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

grpc:
  server:
    port: 9090

